"""HTTP routes for the pipeline API.

Every pipeline stage is exposed on its own multipart/form-data endpoint
(image processing, renderer, caption) and `POST /posts` runs all of them.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import APIRouter, Depends, File, Form, HTTPException, Path, UploadFile, status
from fastapi.responses import FileResponse

from ..config import ROOT_DIR, load_config
from .models import CaptionResponse, ErrorResponse, HealthResponse, ImageKind, PostResponse
from .service import API_PREFIX, PipelineService

router = APIRouter()

_EMPTY_UPLOAD_DETAIL = "Upload is empty."
_IMAGE_RESPONSES: dict[int | str, dict[str, Any]] = {
    status.HTTP_200_OK: {
        "content": {"image/png": {}},
        "description": "The generated 1:1 PNG image.",
    },
    status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse, "description": "Empty upload."},
    status.HTTP_500_INTERNAL_SERVER_ERROR: {
        "model": ErrorResponse,
        "description": "The stage failed.",
    },
}


def get_pipeline_service() -> PipelineService:
    """Provide the service, loading config lazily so imports stay side-effect free."""
    return PipelineService(config=load_config(), output_root=ROOT_DIR / "output" / "api")


def _read_upload(photo: UploadFile) -> bytes:
    """Read the upload synchronously; sync endpoints run in a worker thread.

    Playwright's sync API (used by the composition/render stages) cannot run
    inside the asyncio event loop, so every stage endpoint is a plain `def`.
    """
    content = photo.file.read()
    if not content:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=_EMPTY_UPLOAD_DETAIL)
    return content


@router.get(
    "/health",
    response_model=HealthResponse,
    tags=["system"],
    summary="Service health",
    description="Returns `ok` when the API process is accepting requests.",
)
def health() -> HealthResponse:
    return HealthResponse(status="ok")


# --- Step 1: image processing ----------------------------------------------


@router.post(
    "/image-processing",
    response_class=FileResponse,
    tags=["image-processing"],
    summary="Compose the 1:1 bordered image",
    description=(
        "Step 1. Accepts a source photo as `multipart/form-data` and returns the exact "
        "1:1 bordered PNG: the photo is centered on a solid background with a minimum "
        "border, scaled with `object-fit: contain` so it is never cropped or stretched."
    ),
    responses=_IMAGE_RESPONSES,
)
def compose_image(
    photo: Annotated[
        UploadFile,
        File(description="Source photo (JPEG, PNG or WebP) to compose."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
) -> FileResponse:
    content = _read_upload(photo)
    result = service.compose(filename=photo.filename or "upload.jpg", content=content)
    return FileResponse(result.path, media_type="image/png", filename=result.path.name)


# --- Step 2: renderer -------------------------------------------------------


@router.post(
    "/renderer",
    response_class=FileResponse,
    tags=["renderer"],
    summary="Render the metadata card",
    description=(
        "Step 2. Accepts a source photo as `multipart/form-data`, reads its EXIF data "
        "and returns the 1:1 metadata-card PNG. A small map is included when the photo "
        "carries GPS coordinates."
    ),
    responses=_IMAGE_RESPONSES,
)
def render_metadata_card(
    photo: Annotated[
        UploadFile,
        File(description="Source photo (JPEG, PNG or WebP) whose EXIF is rendered."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
) -> FileResponse:
    content = _read_upload(photo)
    card = service.render(filename=photo.filename or "upload.jpg", content=content)
    return FileResponse(card, media_type="image/png", filename=card.name)


# --- Step 3: caption --------------------------------------------------------


@router.post(
    "/caption",
    response_model=CaptionResponse,
    tags=["caption"],
    summary="Generate a caption",
    description=(
        "Step 3. Accepts a source photo as `multipart/form-data` and returns a caption "
        "generated by the configured vision LLM, with the configured hashtags appended. "
        "The standalone caption is generated from the uploaded photo itself."
    ),
    responses={
        status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse, "description": "Empty upload."},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": ErrorResponse,
            "description": "The caption model call failed.",
        },
    },
)
def generate_caption_endpoint(
    photo: Annotated[
        UploadFile,
        File(description="Source photo (JPEG, PNG or WebP) to caption."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
) -> CaptionResponse:
    content = _read_upload(photo)
    caption = service.caption(filename=photo.filename or "upload.jpg", content=content)
    return CaptionResponse(caption=caption)


# --- Full pipeline ----------------------------------------------------------


@router.post(
    "/posts",
    response_model=PostResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["posts"],
    summary="Upload a photo and run the full pipeline",
    description=(
        "Runs every step in order: image processing, renderer, caption, and (optionally) "
        "the Instagram upload.\n\n"
        "When `caption` is omitted the caption is generated with the configured vision "
        "LLM from the composed image. When `publish` is omitted it defaults to the inverse "
        "of `upload.dry_run` in `config.yaml`, so the API never posts unless explicitly asked."
    ),
    responses={
        status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse, "description": "Empty upload."},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": ErrorResponse,
            "description": "A pipeline step failed.",
        },
    },
)
def create_post(
    photo: Annotated[
        UploadFile,
        File(description="Source photo (JPEG, PNG or WebP) to process."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
    caption: Annotated[
        str | None,
        Form(description="Override the LLM caption. Generated when omitted."),
    ] = None,
    publish: Annotated[
        bool | None,
        Form(description="Send the post to Instagram. Defaults to `not upload.dry_run`."),
    ] = None,
) -> PostResponse:
    content = _read_upload(photo)
    return service.create_post(
        filename=photo.filename or "upload.jpg",
        content=content,
        caption_override=caption,
        publish=publish,
    )


@router.get(
    "/posts/{post_id}/images/{kind}",
    response_class=FileResponse,
    tags=["posts"],
    summary="Download a generated image",
    description="Fetch one of the 1:1 PNG images produced for a previous upload.",
    responses={
        status.HTTP_200_OK: {
            "content": {"image/png": {}},
            "description": "The requested PNG image.",
        },
        status.HTTP_404_NOT_FOUND: {
            "model": ErrorResponse,
            "description": "Unknown post id or image kind.",
        },
    },
)
def get_generated_image(
    post_id: Annotated[
        str,
        Path(description="Post id returned by the upload endpoint."),
    ],
    kind: Annotated[
        ImageKind,
        Path(description="Which generated image to download."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
) -> FileResponse:
    image = service.resolve_image(post_id, kind)
    if image is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Image not found for this post id.",
        )
    return FileResponse(image, media_type="image/png", filename=image.name)


__all__ = ["router", "get_pipeline_service", "API_PREFIX"]
