"""POST /caption — Step 3: generate an LLM caption."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, File, UploadFile, status

from ...dependencies import get_pipeline_service, read_upload
from ...models import CaptionResponse, ErrorResponse
from ...service import PipelineService

router = APIRouter()


@router.post(
    "/caption",
    response_model=CaptionResponse,
    tags=["caption"],
    summary="Generate a caption",
    description=(
        "Step 3. Accepts a source photo as `multipart/form-data` and returns a caption "
        "generated by the configured vision LLM, with the configured hashtags appended. "
        "The standalone caption is generated from the uploaded photo itself."
    ),
    responses={
        status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse, "description": "Empty upload."},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": ErrorResponse,
            "description": "The caption model call failed.",
        },
    },
)
def generate_caption_endpoint(
    photo: Annotated[
        UploadFile,
        File(description="Source photo (JPEG, PNG or WebP) to caption."),
    ],
    service: Annotated[PipelineService, Depends(get_pipeline_service)],
) -> CaptionResponse:
    content = read_upload(photo)
    caption = service.caption(filename=photo.filename or "upload.jpg", content=content)
    return CaptionResponse(caption=caption)
