{{- if and .Values.image.auth.username .Values.image.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instagram-pipeline.registrySecretName" . }}
  labels:
    {{- include "instagram-pipeline.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "instagram-pipeline.dockerconfigjson" . | b64enc | quote }}
{{- end }}
