apiVersion: v1
kind: Service
metadata:
  name: {{ include "instagram-pipeline.fullname" . }}
  labels:
    {{- include "instagram-pipeline.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "instagram-pipeline.selectorLabels" . | nindent 4 }}
